In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from youngnet import nn

In [4]:
data1 = pd.read_csv('../LR_dataset/data1.csv', header=None)
data2 = pd.read_csv('../LR_dataset/data2.csv', header=None)
data1 = data1.values
data2 = data2.values
data1_x = data1[:, :-1]
data1_y = nn.onehot(data1[:, -1].astype(int).reshape(-1), 2)
data2_x = data2[:, :-1]
data2_y = nn.onehot(data2[:, -1].astype(int).reshape(-1), 2)

In [18]:
train_data1_x, test_data1_x, train_data1_y, test_data1_y = nn.train_test_split(data1_x, data1_y, test_size=len(data1_x)//8)
train_data2_x, test_data2_x, train_data2_y, test_data2_y = nn.train_test_split(data2_x, data2_y, test_size=len(data2_x)//8)

In [17]:
data2_x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [19]:
train_data2_x

array([[  2.   ,  85.   ,  65.   , ...,  39.6  ,   0.93 ,  27.   ],
       [  1.   ,  81.   ,  72.   , ...,  26.6  ,   0.283,  24.   ],
       [  0.   , 101.   ,  62.   , ...,  21.9  ,   0.336,  25.   ],
       ...,
       [  2.   , 106.   ,  56.   , ...,  29.   ,   0.426,  22.   ],
       [  1.   , 147.   ,  94.   , ...,  49.3  ,   0.358,  27.   ],
       [  2.   ,  93.   ,  64.   , ...,  38.   ,   0.674,  23.   ]])

In [8]:
train_data1_x

array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e+00, 1.000e+00,
        3.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 5.466e+00, 2.200e+01,
        8.200e+01],
       [1.400e-01, 1.400e-01, 2.900e-01, ..., 2.686e+00, 7.300e+01,
        3.680e+02],
       ...,
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 1.560e+00, 9.000e+00,
        6.400e+01],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 2.576e+00, 1.400e+01,
        6.700e+01],
       [0.000e+00, 5.500e-01, 5.500e-01, ..., 4.761e+00, 1.400e+02,
        2.000e+02]])

In [10]:
train_data1_x_copy = train_data1_x.copy()
train_data1_y_copy = train_data1_y.copy()
test_data1_x_copy = test_data1_x.copy()
test_data1_y_copy = test_data1_y.copy()

In [11]:
test

NameError: name 'test' is not defined

In [12]:
test_data1_x

array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 1.259e+00, 3.000e+00,
        3.400e+01],
       [0.000e+00, 3.400e-01, 6.800e-01, ..., 3.131e+00, 1.300e+01,
        1.190e+02],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 8.476e+00, 6.800e+01,
        3.560e+02],
       ...,
       [0.000e+00, 0.000e+00, 5.800e-01, ..., 3.281e+00, 6.400e+01,
        3.610e+02],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 3.368e+00, 7.000e+00,
        6.400e+01],
       [0.000e+00, 0.000e+00, 9.100e-01, ..., 2.032e+00, 1.200e+01,
        1.260e+02]])

In [20]:
train_data1_x_copy, test_data1_x_copy = nn.standardization(train_data1_x_copy, test_data1_x_copy)
train_data2_x_copy, test_data2_x_copy = nn.standardization(train_data2_x, test_data2_x)

In [21]:
train_data2_x_copy

array([[-0.52950694, -1.13894755, -0.19140219, ...,  0.96221417,
         1.36345405, -0.51172242],
       [-0.8275209 , -1.26509577,  0.1703318 , ..., -0.67761006,
        -0.57228349, -0.77355806],
       [-1.12553486, -0.6343547 , -0.34643105, ..., -1.27046959,
        -0.41371457, -0.68627951],
       ...,
       [-0.52950694, -0.47666943, -0.65648876, ..., -0.37487328,
        -0.1444466 , -0.94811515],
       [-0.8275209 ,  0.81634978,  1.30721008, ...,  2.18577533,
        -0.34789351, -0.51172242],
       [-0.52950694, -0.88665113, -0.24307848, ...,  0.76038965,
         0.59753626, -0.8608366 ]])